baseurl: "/API-Kennisbank"
apiname: "API-Kennisbank"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: Kennisbank over standaardiseren van API-specificaties
    subnav:
      - title: Main
        path: /
      - title: Implementatieoverwegingen
        path: /API Implementatie/Implementatie overwegingen
      - title: Gitflow
        path: /GitFlow/Gitflow_implementatie
      - title: VNGR API Design Rules
        path: /Design rules/inhoud

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: VNG-Realisatie/jekyll-theme-vng-realisatie

github: VNG-Realisatie/API-kennisbank

theme: jekyll-theme-time-machine

project_name: /API-Kennisbank

standard_family: VNG Realisatie
